# Generated by Django 4.0 on 2022-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('order_type', models.CharField(choices=[('mar', 'Market Order'), ('lim', 'Limit Order')], default='mar', max_length=3)),
            ],
        ),
    ]
