# Generated by Django 4.0 on 2022-01-09 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("oms_app", "0002_order_action_order_expiry_order_placed_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AddField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="action",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell"), ("pending", "Pending")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
