# Generated by Django 4.0 on 2022-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oms_app", "0003_remove_order_id_order_uuid_alter_order_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
