# Generated by Django 4.0 on 2022-01-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oms_app", "0005_rename_price_order_min_price_order_max_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="min_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="max_price",
        ),
    ]
