# Generated by Django 4.0 on 2022-01-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oms_app", "0006_rename_min_price_order_price_remove_order_max_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.CharField(default="kdp2", max_length=200),
            preserve_default=False,
        ),
    ]
